service: swimpool-crowd-statistics
useDotenv: true
variablesResolutionMode: 20210326
plugins:
  - serverless-offline
provider:
  lambdaHashingVersion: 20201221
  name: aws
  runtime: nodejs14.x
  region: ap-southeast-1
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    MONGO_USER: ${ssm:/lambda/ahorro/prod/MONGO_USER}
    MONGO_PASSWORD: ${ssm:/lambda/ahorro/prod/MONGO_PASSWORD}
    MONGO_PATH: ${ssm:/lambda/swimpool/prod/MONGO_PATH}
package:
  individually: true
functions:
  crawlSwimpoolCrowd:
    handler: handlers/crawlSwimpoolCrowd.handler
    events:
      - schedule: cron(0,30 0-13,23 * * ? *)
  fetchCrowdData:
    handler: handlers/fetchCrowdData.handler
    events:
      - httpApi:
          method: GET
          path: /crowd
  fetchCrowdDailyData:
    handler: handlers/fetchCrowdDailyData.handler
    events:
      - httpApi:
          method: GET
          path: /crowd/daily



